services:
  kennedy-yolo-client:
    image: kipanch/yolo-client:v1.0.3
    build: ./client
    container_name: app-yolo-client
    ports:
      - "3000:80"
    depends_on: 
      - kennedy-yolo-backend
    networks:
      - app-net

  kennedy-yolo-backend:
    image: kipanch/yolo-backend:v1.0.3
    build: ./backend
    container_name: app-yolo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://app-mongo:27017/yolomy
    depends_on: 
      - app-mongo
    networks:
      - app-net

  app-mongo:
    image: mongo
    container_name: app-mongo
    restart: always
    networks:
      - app-net
    volumes:
      - app-mongo-data:/data/db

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - ip_range: 172.20.0.0/16

volumes:
  app-mongo-data:
    driver: local