version: "3.8"
services:
  # Frontend microservice
  kennedy-yolo-client:
    image: kipanch/yolo-client:latest
    build: ./client
    container_name: brian-yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - kennedy-yolo-backend
    networks:
      - app-net

  # Backend microservice
  kennedy-yolo-backend:
    image: kipanch/yolo-backend:latest
    build: ./backend
    container_name: brian-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Point to FerretDB instead of MongoDB
      - MONGODB_URI=mongodb://ferretdb:27017/myapp?authMechanism=PLAIN
    depends_on: 
      - app-ferretdb
    networks:
      - app-net

  # FerretDB service (MongoDB-compatible layer)
  app-ferretdb:
    image: kipanch/yolo-ferretdb:latest
    build: ./ferretdb
    container_name: app-ferretdb
    restart: always
    ports:
      - "27017:27017"
    depends_on:
      - app-postgres
    networks:
      - app-net

  # PostgreSQL database (actual data storage)
  app-postgres:
    image: kipanch/yolo-postgres:latest
    build: ./database
    container_name: app-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
    networks:
      - app-net
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d:ro

# Network configuration
networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

# Persistent storage
volumes:
  app-postgres-data:
    driver: local